"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../lib/Provider";
import { ToastContainer } from "react-toastify";
import { SetStateAction, useEffect, useState } from "react";
import Navber from "@/components/ui/Header";
import NavigationBar from "@/components/ui/NavigationBar";
import { useGetProfileQuery } from "@/redux/api/auth/authSlice";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let [userLoggedIn, setUserLoggedIn] = useState(false);
  let [loading, setLoading] = useState(true);
  let [user, setUser] = useState(null);

  useEffect(() => {
    if (localStorage.getItem("token")) {
      setLoading(false);
      setUser(localStorage.getItem("token") as SetStateAction<null>);
    } else {
      setUserLoggedIn(false);
      setUser(null);
    }
  }, [userLoggedIn, user, loading]);
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          <NavigationBar></NavigationBar>
          {children}
        </body>
      </html>
    </Providers>
  );
}
